#!/bin/sh
nohup python3 -u main.py \
    -iwslt \
    -maxlen 100 \
    -minfreq 2 \
    -pth_tr "../../data/" \
    -stp 10 \
    -bs 16 \
    -evalee 10 \
    -sos "<s>" \
    -eos "</s>" \
    -cuda \
    -emptymem \
    -nl 6 \
    -nh 8 \
    -dk 64 \
    -dv 64 \
    -dm 512 \
    -df 1024 \
    -drop 0.1 \
    -thres 0.999 \
    -lws \
    -eps 0.1 \
    -warm 4000 \
    -save \
    -savebest \
    -svp ./model/transformer.chkpt > ./logs/transformer.log &