#!/bin/sh
CUDA_LAUNCH_BLOCKING=1 nohup python3 -u main.py \
    -iwslt \
    -maxlen 50 \
    -minfreq 2 \
    -pth_tr "../../data/" \
    -stp 20 \
    -bs 32 \
    -pee 12 \
    -sos "<s>" \
    -eos "</s>" \
    -cuda \
    -emptymem \
    -nl 6 \
    -nh 8 \
    -dk 64 \
    -dv 64 \
    -dm 512 \
    -df 2048 \
    -drop 0.1 \
    -thres 0.9999 \
    -eps 0.1 \
    -warm 4000 \
    -save \
    -savebest \
    -svp ./model/transformer.chkpt > ./logs/transformer.log &
